import { useEffect } from 'react';
import { Platform } from 'react-native';
import * as Application from 'expo-application';
import { useGiftStore } from '@/lib/stores/gift.store';

/** Gift codes are 128-bit base64url strings generated by the backend. */
export const GIFT_CODE_REGEX = /^[A-Za-z0-9_-]{16,64}$/;

/**
 * One-shot read of the Play Store install referrer on first launch.
 * The share link carries `referrer=utm_source=gift&gift_code=<code>`;
 * when present, the code is stored as the pending gift so it survives
 * signup and is claimed right after onboarding.
 *
 * Only works for installs coming from the Play Store — sideloaded APKs
 * arrive without a referrer, which is why manual code entry also exists.
 */
export function useInstallReferrer() {
  const hydrated = useGiftStore((s) => s._hydrated);
  const referrerChecked = useGiftStore((s) => s.referrerChecked);

  useEffect(() => {
    if (!hydrated || referrerChecked || Platform.OS !== 'android') return;
    let cancelled = false;

    (async () => {
      try {
        const referrer = await Application.getInstallReferrerAsync();
        if (cancelled || !referrer) return;
        // Referrer is untrusted external input: parse defensively and
        // validate the code format before storing.
        const code = new URLSearchParams(referrer).get('gift_code');
        if (code && GIFT_CODE_REGEX.test(code)) {
          useGiftStore.getState().setPendingGiftCode(code);
        }
      } catch {
        // Referrer unavailable (sideload, emulator) — manual entry covers it.
      } finally {
        if (!cancelled) useGiftStore.getState().setReferrerChecked();
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [hydrated, referrerChecked]);
}
